# Generated by Django 5.2.13 on 2026-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_unit_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='Ед. измерения'),
        ),
    ]
